DROP TABLE IF EXISTS TEPPICH;
DROP TABLE IF EXISTS LAGER;

CREATE TABLE LAGER
(
    ID   IDENTITY PRIMARY KEY,
    NAME VARCHAR(100)
);

CREATE TABLE TEPPICH
(
    ID          IDENTITY PRIMARY KEY,
    BEZEICHNUNG VARCHAR(100),
    FARBE       VARCHAR(100),
    PREIS       DECIMAL,
    MENGE       INT,
    FK_LAGER  BIGINT,
    CONSTRAINT FK_TEPPICH_LAGER FOREIGN KEY (FK_LAGER) REFERENCES LAGER (ID)
);